<?php

namespace Proxies\__CG__\SocialFunding\Core\SharedBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \SocialFunding\Core\SharedBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'integrationEnginePartner', 'campaignProducts', 'code', 'name', 'description', 'integrationEngineCategory', 'codeManufacturer', 'nameManufacturer', 'imageSmall', 'imageAverage', 'imageBig', 'keywords', 'codeSku', 'priceFrom', 'priceTo', 'available', 'availability', 'specification', 'technicalSpecification', 'inDatabase');
        }

        return array('__isInitialized__', 'id', 'integrationEnginePartner', 'campaignProducts', 'code', 'name', 'description', 'integrationEngineCategory', 'codeManufacturer', 'nameManufacturer', 'imageSmall', 'imageAverage', 'imageBig', 'keywords', 'codeSku', 'priceFrom', 'priceTo', 'available', 'availability', 'specification', 'technicalSpecification', 'inDatabase');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntegrationEnginePartner($integrationEnginePartner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntegrationEnginePartner', array($integrationEnginePartner));

        return parent::setIntegrationEnginePartner($integrationEnginePartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntegrationEnginePartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntegrationEnginePartner', array());

        return parent::getIntegrationEnginePartner();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeManufacturer($codeManufacturer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeManufacturer', array($codeManufacturer));

        return parent::setCodeManufacturer($codeManufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeManufacturer', array());

        return parent::getCodeManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameManufacturer($nameManufacturer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameManufacturer', array($nameManufacturer));

        return parent::setNameManufacturer($nameManufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameManufacturer', array());

        return parent::getNameManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageSmall($imageSmall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageSmall', array($imageSmall));

        return parent::setImageSmall($imageSmall);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageSmall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageSmall', array());

        return parent::getImageSmall();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageAverage($imageAverage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageAverage', array($imageAverage));

        return parent::setImageAverage($imageAverage);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageAverage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageAverage', array());

        return parent::getImageAverage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageBig($imageBig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageBig', array($imageBig));

        return parent::setImageBig($imageBig);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageBig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageBig', array());

        return parent::getImageBig();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords($keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', array($keywords));

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', array());

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeSku($codeSku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeSku', array($codeSku));

        return parent::setCodeSku($codeSku);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeSku', array());

        return parent::getCodeSku();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceFrom($priceFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceFrom', array($priceFrom));

        return parent::setPriceFrom($priceFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceFrom', array());

        return parent::getPriceFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceTo($priceTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceTo', array($priceTo));

        return parent::setPriceTo($priceTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceTo', array());

        return parent::getPriceTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable($available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', array($available));

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailable', array());

        return parent::getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailability($availability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailability', array($availability));

        return parent::setAvailability($availability);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailability()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailability', array());

        return parent::getAvailability();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecification($specification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecification', array($specification));

        return parent::setSpecification($specification);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecification', array());

        return parent::getSpecification();
    }

    /**
     * {@inheritDoc}
     */
    public function setTechnicalSpecification($technicalSpecification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTechnicalSpecification', array($technicalSpecification));

        return parent::setTechnicalSpecification($technicalSpecification);
    }

    /**
     * {@inheritDoc}
     */
    public function getTechnicalSpecification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTechnicalSpecification', array());

        return parent::getTechnicalSpecification();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntegrationEngineCategory($integrationEngineCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntegrationEngineCategory', array($integrationEngineCategory));

        return parent::setIntegrationEngineCategory($integrationEngineCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntegrationEngineCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntegrationEngineCategory', array());

        return parent::getIntegrationEngineCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addCampaignProduct(\SocialFunding\Core\SharedBundle\Entity\CampaignProducts $campaignProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCampaignProduct', array($campaignProducts));

        return parent::addCampaignProduct($campaignProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCampaignProduct(\SocialFunding\Core\SharedBundle\Entity\CampaignProducts $campaignProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCampaignProduct', array($campaignProducts));

        return parent::removeCampaignProduct($campaignProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampaignProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampaignProducts', array());

        return parent::getCampaignProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setInDatabase($inDatabase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInDatabase', array($inDatabase));

        return parent::setInDatabase($inDatabase);
    }

    /**
     * {@inheritDoc}
     */
    public function getInDatabase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInDatabase', array());

        return parent::getInDatabase();
    }

}
