security:

    providers:
        chain_provider:
            chain:
#                providers: [fos_userbundle]
                providers: [fos_userbundle, shared_fos_facebook]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        shared_fos_facebook:
            id: my.facebook.user

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false

        public:
            pattern:   ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/socialfundinglogin/"
                server_url: "http://socialfunding.dev.br/"
                login_path: /loginfb
                check_path: /loginfb_check
                provider: shared_fos_facebook
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /ong/perfil
            anonymous: true
            logout:    true

    access_control:
        - { path: ^/checkout/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar/ong, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
